---
title: "Predicting resilience with 16S data"
output: html_notebook
date: April 26th, 2019
---


# Load data


```{r}
library(tidyverse)
library(phyloseq)
library(RColorBrewer)
```

```{r}
ps <- readRDS("../../data/16S/phyloseq/perturb_physeq_fltr2430_17Jul18.rds")
ps
```

```{r}
SMP <- data.frame(ps@sam_data, stringsAsFactors = FALSE) %>%
  mutate(SampleDepth = sample_sums(ps))
  
SUBJ <-  SMP %>%
  select(Subject, Group, Age:BMI) %>%
  distinct()
```


```{r}
data.frame(ps@sam_data) %>%
    select(Group, Subject) %>%
    distinct() %>%
    group_by(Group) %>%
    summarise(subject_count = n())
```

```{r, eval = FALSE}
# Transform counts to not "over-weight" highly abundant taxa
ps_asinh <- transform_sample_counts(ps, function(x) {asinh(x)})
brayD.ihs <- phyloseq::distance(ps_asinh, method = "bray")

class(brayD.ihs)
```



```{r, eval = FALSE}
brayD.df <- reshape2::melt(
  as.matrix(brayD.ihs), 
  varnames = c("Sample_1", "Sample_2"),
  value.name = "bray") %>%
  mutate(Sample_1 = as.character(Sample_1),
         Sample_2 = as.character(Sample_2))
dim(brayD.df)
```



```{r, eval = FALSE}
brayD.df <- brayD.df[, 1:3]
brayD.df <- brayD.df %>%
  left_join(
    SMP %>% select(Meas_ID, Subject), 
    by = c("Sample_1" = "Meas_ID"))

brayD.df <- brayD.df %>%
  left_join(
    SMP %>% select(Meas_ID, Subject), 
    by = c("Sample_2" = "Meas_ID"), 
    suffix = c("_1", "_2"))
 
head(brayD.df)   
```


```{r}
brayD.df <- brayD.df %>%
    filter(Subject_1 == Subject_2) %>%
    rename(Subject = Subject_1) %>%
    select(-Subject_2)
dim(brayD.df)
head(brayD.df)
```



```{r}
abx_brayD.df <- brayD.df %>%
    left_join(
        SMP %>% select(Meas_ID, Group, Abx_Interval, Abx_RelDay), 
        by = c("Sample_1" = "Meas_ID")) %>%
    left_join(
        SMP %>% select(Meas_ID, Group, Abx_Interval, Abx_RelDay), 
        by = c("Sample_2" = "Meas_ID"), suffix = c("_1", "_2")) %>%
        filter(grepl("Abx", Group_1), grepl("Abx", Group_2),  
               Abx_RelDay_1 > -50, Abx_RelDay_2 > -50) 
dim(abx_brayD.df)
```

Measures for variability

```{r}
daily_variability <- abx_brayD.df %>%
    mutate(day_diff = abs(Abx_RelDay_2 - Abx_RelDay_1)) %>%
    filter(day_diff < 3, Abx_RelDay_1 >= -10, Abx_RelDay_2 < 0,
           Abx_RelDay_2 > Abx_RelDay_1) 
    
daily_variability_mean <- daily_variability %>%
    group_by(Subject) %>%
    summarise(mean_bray = mean(bray), n_baseline_samp = n()) 
```


```{r}
ggplot(
  daily_variability_mean,
  aes(x = bray, y = stabilization_time)) +
  geom_text(aes(label = Subject, color = diff_max), size = 4, fontface = "bold") +
  scale_color_viridis() +
  xlab("Daily Variability at [-7, 0] measured with Bray-Curtis")
```

```{r}
ggplot(
  daily_variability_mean,
  aes(x = unifrac, y = stabilization_time)) +
  geom_text(aes(label = Subject, color = diff_max), size = 4, fontface = "bold") +
  scale_color_viridis() +
  xlab("Daily Variability at [-7, 0] measured with Unifrac")
```


```{r}
ggplot(
  daily_variability_mean,
  aes(x = jaccard, y = diff_max)) +
  geom_text(aes(label = Subject, color = diff_max), size = 4, fontface = "bold") +
  scale_color_viridis() +
  xlab("Daily Variability at [-7, 0] measured with Jaccard")
```

```{r}
daily_variability_mean %>%
  summarise_at(
    .vars = c("bray", "jaccard", "unifrac"),
    .funs = function(x)
      cor(x,daily_variability_mean$stabilization_time, method = "spearman")
  )
```


Measures for recovery

```{r}
abx_brayD_mean <- abx_brayD.df %>%
    rename(Subject = Subject_1) %>%
    select(-Subject_2) %>%
    filter(Abx_RelDay_1 >= -7 & Abx_RelDay_1 < 0) %>%
    group_by(Subject, Sample_2, Group_2, Abx_Interval_2, Abx_RelDay_2) %>%
    summarize(mean_bray = mean(bray))

abx_brayD_mean <- abx_brayD_mean %>%
    rename(Sample = Sample_2, Group = Group_2, Abx_Interval = Abx_Interval_2, 
           Abx_RelDay = Abx_RelDay_2)
dim(abx_brayD_mean)  
```

```{r, fig.width=8}
abx_brayD_mean %>%
ggplot(aes(x =Abx_RelDay, y = mean_bray, group = Subject, color = Abx_Interval)) +
    geom_point() + geom_line(aes(group = Subject)) +
    theme(legend.position = "bottom")
```


```{r, fig.width=8}
abx_brayD_mean %>%
ggplot(aes(x =Abx_RelDay, y = mean_bray, group = Subject, color = Abx_Interval)) +
    geom_text(aes(label = Subject)) + geom_line(aes(group = Subject)) +
    theme(legend.position = "bottom")
```

```{r}
length(unique(abx_brayD_mean$Subject))
```

```{r}
unique(abx_brayD_mean$Group)
```






```{r}
abx_DistBray <- abx_brayD.df %>%
    select(Sample_1, Sample_2, Subject, Group, contains("Abx")) %>%
    group_by(Sample_2) %>%
    
```




# Session Info

```{r}
sessionInfo()
```

