---
title: "adapted functions"
output: html_document
---

```{r rewrite PPCA functions so that I can use them with my high number of variables}

library(MetabolAnalyze)

#rewrite function ppca.metabol() so that it doesn't have an upper limit of 375 variables: 

#introduce a new output value "man.sdev" that calucates the standard deviations of the PCs to be used in later plotting


ppca.metabol.SR <- function (Y, minq = 1, maxq = 2, scale = "none", epsilon = 0.1, 
    plot.BIC = FALSE, printout = TRUE) 
{
    if (missing(Y)) {
        stop("Spectral data are required to fit the PPCCA model.\n")
    }
    if (minq > maxq) {
        stop("minq can not be greater than maxq.\n")
    }
    if (maxq > ncol(Y)) {
        stop("maxq can not be greater than the number of variables.\n")
    }
    if (maxq > 30) {
        cat("Warning! Model fitting may become unstable for q > 30.\n\n")
    }
    if (epsilon > 1) {
        cat("Warning! Poor model covergence expected for epsilon > 1.\n")
    }
    if (epsilon < 1e-04) {
        cat("Warning! Model covergence becomes very slow for epsilon < 0.0001.\n")
    }
    V <- 5000
    N <- nrow(Y)
    p <- ncol(Y)
    Sig_q <- rep(0, maxq)
    W_q <- list()
    U_q <- list()
    AIC <- rep(0, maxq)
    BIC <- rep(0, maxq)
    ll <- matrix(0, maxq, V)
    lla <- matrix(0, maxq, V)
    Y <- as.matrix(scaling(Y, type = scale))
    Vp <- 10
    C2p <- p * 3
    muhat <- colMeans(Y)
    Yc <- sweep(Y, 2, muhat, "-")
    S <- (1/nrow(Yc)) * (t(Yc) %*% Yc)
    temp <- eigen(S)
    for (q in minq:maxq) {
        Sig <- abs((1/(p - q)) * sum(temp$val[(q + 1):p]))
        W <- temp$vec[, 1:q]
        u <- t(cmdscale(dist(Y), q))
        tol <- epsilon + 1
        v <- 0
        while (tol > epsilon) {
            v <- v + 1
            k <- S %*% W
            M_1 <- solve((t(W) %*% W + Sig * diag(q)))
            W <- k %*% solve(Sig * diag(q) + (M_1 %*% t(W)) %*% 
                k)
            MLESig <- (1/p) * sum(diag(S - k %*% (M_1 %*% t(W))))
            Sig <- c(((N * p) * MLESig + C2p)/((N * p) + Vp + 
                2))
            u <- M_1 %*% (t(W) %*% t(Yc))
            ll[q, v] <- sum(dmvnorm(Y, muhat, W %*% t(W) + Sig * 
                diag(p), log = TRUE))
            converge <- Aitken(ll, lla, v, q, epsilon)
            tol <- converge[[1]]
            lla[q, v] <- converge[[2]]
            if (v == V) {
                if (printout == TRUE) {
                  cat("Algorithm stopped for q = ", q, ". Maximum number of iterations exceeded.\n\n")
                }
                tol <- epsilon - 1
            }
        }
        if (printout == TRUE) {
            cat("q = ", q, ": PPCA converged.\n\n")
        }
        params <- (p * q) - (0.5 * q * (q - 1)) + 1
        AIC[q] <- (2 * ll[q, v]) - (2 * params)
        BIC[q] <- (2 * ll[q, v]) - (params * log(N))
        U_q[[q]] <- u
        Sig_q[q] <- Sig
        W_q[[q]] <- W
    }
    qopt <- c(minq:maxq)[BIC[minq:maxq] == max(BIC[minq:maxq])]
    Uopt <- t(U_q[[qopt]])
    Wopt <- W_q[[qopt]]
    Sigopt <- Sig_q[qopt]
    if (plot.BIC == TRUE) {
        plot(minq:maxq, BIC[minq:maxq], type = "b", xlab = "q", 
            ylab = "BIC", col.lab = "blue")
        abline(v = qopt, col = "red", lty = 2)
    }
    list(q = qopt, sig = Sigopt, scores = Uopt, loadings = Wopt, 
        BIC = BIC[minq:maxq], AIC = AIC[minq:maxq])
}


#changed the number of selected bins to nSL, that is the number of variables significantly different from zero (before that, it asked for the number of bins to select, which made it difficult to run the function in a loop)

ppca.metabol.jack.SR <- function (Y, minq = 1, maxq = 2, scale = "none", epsilon = 0.1, 
    conflevel = 0.95) 
{
    if (missing(Y)) {
        stop("Spectral data are required to fit the PPCCA model.\n")
    }
    if (minq > maxq) {
        stop("minq can not be greater than maxq.\n")
    }
    if (maxq > ncol(Y)) {
        stop("maxq can not be greater than the number of variables.\n")
    }
    if (maxq > 30) {
        cat("Warning! Model fitting may become unstable for q > 30.\n\n")
    }
    if (epsilon > 1) {
        cat("Warning! Poor model covergence expected for epsilon > 1.\n")
    }
    if (epsilon < 1e-04) {
        cat("Warning! Model covergence becomes very slow for epsilon < 0.0001.\n")
    }
    Vj <- 5000
    N <- nrow(Y)
    p <- ncol(Y)
    modelfit <- ppca.metabol.SR(Y, minq, maxq, scale = scale, epsilon, 
        plot.BIC = FALSE, printout = FALSE)
    q <- modelfit$q
    Wj <- Wopt <- modelfit$loadings
    Sigj <- Sigopt <- modelfit$sig
    Uopt <- modelfit$scores
    BIC <- modelfit$BIC
    AIC <- modelfit$AIC
    cat("PPCA fitted to all ", N, " observations. Optimal model has", 
        q, "factors.\n \n")
    Sigstore <- rep(NA, N)
    Wstore <- array(0, c(p, q, N))
    ll <- matrix(0, q, Vj)
    lla <- matrix(0, q, Vj)
    cat("Using the jackknife to estimate parameter uncertainty...\n \n")
    for (n in 1:N) {
        J <- Y[-n, ]
        J <- scaling(J, scale)
        Vp <- 10
        C2p <- p * 3
        muhat <- colMeans(J)
        Jc <- sweep(J, 2, muhat, "-")
        Sj <- (1/nrow(Jc)) * (t(Jc) %*% Jc)
        tol <- epsilon + 1
        v <- 0
        while (tol > epsilon) {
            v <- v + 1
            if (v == 1) {
                Wj <- Wopt
                Sigj <- Sigopt
                uj <- t(Uopt[-n, ])
            }
            k <- Sj %*% Wj
            M_1 <- solve((t(Wj) %*% Wj + Sigj * diag(q)))
            Wj <- k %*% solve(Sigj * diag(q) + (M_1 %*% t(Wj)) %*% 
                k)
            MLESigj <- (1/p) * sum(diag(Sj - k %*% (M_1 %*% t(Wj))))
            Sigj <- c(((N * p) * MLESigj + C2p)/((N * p) + Vp + 
                2))
            uj <- M_1 %*% (t(Wj) %*% t(Jc))
            ll[q, v] <- sum(dmvnorm(J, muhat, Wj %*% t(Wj) + 
                Sigj * diag(p), log = TRUE))
            converge <- Aitken(ll, lla, v, q, epsilon)
            tol <- converge[[1]]
            lla[q, v] <- converge[[2]]
        }
        Sigstore[n] <- Sigj
        Wstore[, , n] <- Wj
    }
    se_W <- sqrt((N - 1)^2/N * (apply(Wstore, c(1, 2), var)))
    UpperCI_W <- Wopt + (qnorm(conflevel + ((1 - conflevel)/2)) * 
        se_W)
    LowerCI_W <- Wopt - (qnorm(conflevel + ((1 - conflevel)/2)) * 
        se_W)
    CI_W <- cbind(LowerCI_W[, 1], UpperCI_W[, 1])
    colnames(CI_W) <- c("LowCI_PC1", "UppCI_PC1")
    ProdciPC1 <- apply(CI_W[, 1:2], 1, prod)
    Signifppmz <- ProdciPC1 > 0
    SignifW <- Wopt[Signifppmz, ]
    nSL <- nrow(SignifW)
    Lower <- as.matrix(LowerCI_W[Signifppmz, ])
    Upper <- as.matrix(UpperCI_W[Signifppmz, ])
    cat("The number of spectral bins with loadings on PC 1 significantly different from 0 is:", 
        nSL, "\n \n")
    grid <- 0.1
    cutoff <- seq(min(abs(SignifW)), max(abs(SignifW)), by = grid)
    nHL <- rep(NA, length(cutoff))
    for (l in 1:length(nHL)) {
        SignifHighppm <- abs(SignifW[, 1]) > cutoff[l]
        SignifHighW <- SignifW[SignifHighppm, ]
        nHL[l] <- sum(SignifHighppm)
    }
    plot(cutoff, nHL, xlab = "Cutoff", ylab = "Number of spectral bins selected", 
        type = "l", cex = 1.2, pch = 21, col = "blue", col.lab = "blue", 
        lwd = 2, main = "Spectral bin selection", col.main = "blue")
    dat <- data.frame(Cutoff = round(cutoff, 2), No.Selected = nHL)
    print(data.frame(dat))
    cat("\n \n")
    number <- nSL   #SR
    cutoff <- cutoff[(nHL == number)][1]
    SignifHighppm <- abs(SignifW[, 1]) > cutoff
    SignifHighW <- matrix(SignifW[SignifHighppm, ], ncol = q)
    LowerH <- matrix(Lower[SignifHighppm, ], ncol = q)
    UpperH <- matrix(Upper[SignifHighppm, ], ncol = q)
    man.sdev <- apply(Uopt, 2, sd) #SR: introduce man.sdev
    barplot2(SignifHighW[, 1], ylim = c(min(LowerH[, 1], 0) - 
        1.5, max(UpperH[, 1], 0) + 1.5), las = 2, width = 0.5, 
        space = 0.5, plot.grid = TRUE, ylab = "PC 1 loadings", 
        xlab = "Spectral regions", names.arg = rownames(SignifW)[SignifHighppm], 
        plot.ci = TRUE, ci.l = LowerH[, 1], ci.u = UpperH[, 1], 
        font.main = 2, col = "red")
    list(q = q, sig = Sigopt, scores = Uopt, loadings = Wopt, 
        SignifW = SignifW, SignifHighW = SignifHighW, Lower = Lower, 
        Upper = Upper, Cutoffs = dat, number = number, cutoff = cutoff, 
        BIC = BIC, AIC = AIC, man.sdev = man.sdev) #SR: introduced man.sdev into ouput
}

```

```{r rewrite PPCCA function}

# for ppcca.metabol.SR function, delete the line which sets a maximum on spectral bins to 375.

#for ppcca.metabol.jack.SR function, set cutoff to the number of spectral bins to the number that has loadings significantly different than zero, rather than ask every time

#for ppcca.metabol.SR function, add man.sdev to the output list.

ppcca.metabol.jack.SR <- function (Y, Covars, minq = 1, maxq = 2, scale = "none", epsilon = 0.1, 
    conflevel = 0.95) 
{
    Y <- as.matrix(Y)
    Covars <- as.matrix(Covars)
    if (missing(Y)) {
        stop("Spectral data are required to fit the PPCCA model.\n")
    }
    if (missing(Covars)) {
        stop("Covariate data are required to fit the PPCCA model.\n ")
    }
    if (nrow(Y) != nrow(Covars)) {
        stop("Spectral data and covariate data should have the same number of rows.\n")
    }
    if (missing(minq)) {
        minq <- 1
    }
    if (missing(maxq)) {
        maxq <- 2
    }
    if (minq > maxq) {
        stop("minq can not be greater than maxq.\n")
    }
    if (maxq > ncol(Y)) {
        stop("maxq can not be greater than the number of variables.\n")
    }
    if (maxq > 10) {
        cat("Warning! Model fitting may become very slow for q > 10.\n\n")
    }
    if (epsilon > 1) {
        cat("Warning! Poor model covergence expected for epsilon > 1.\n")
    }
    if (epsilon < 1e-04) {
        cat("Warning! Model covergence becomes very slow for epsilon < 0.0001.\n")
    }
    Vj <- 40000
    N <- nrow(Y)
    p <- ncol(Y)
    Covars <- as.matrix(Covars, nrow = N, byrow = TRUE)
    L <- ncol(Covars)
    modelfit <- ppcca.metabol.SR(Y, Covars, minq, maxq, scale = scale, 
        epsilon = epsilon, plot.BIC = FALSE, printout = FALSE)
    q <- modelfit$q
    Wj <- Wopt <- modelfit$loadings
    Sigj <- Sigopt <- modelfit$sig
    Alphaj <- Alphaopt <- modelfit$coefficients
    Uopt <- modelfit$scores
    man.sdev <- apply(Uopt, 2, sd) #SR: introduce man.sdev
    BIC <- modelfit$BIC
    AIC <- modelfit$AIC
    Covars <- standardize(Covars)
    Covars <- rbind(rep(1, N), t(Covars))
    if (sum(rownames(Covars) == NULL) == 0) {
        rownames(Covars) <- c(1:(L + 1))
        rownames(Covars)[1] <- "Intercept"
        for (i in 2:(L + 1)) {
            rownames(Covars)[i] <- paste("Covariate", i, sep = "")
        }
    }
    rownames(Covars)[1] <- "Intercept"
    cat("PPCCA fitted to all ", N, " observations. Optimal model has", 
        q, "factors.\n\n")
    Sigstore <- rep(NA, N)
    Wstore <- array(0, c(p, q, N))
    Alphastore <- array(0, c(q, L + 1, nrow(Y)))
    ll <- matrix(0, q, Vj)
    lla <- matrix(0, q, Vj)
    cat("Using the jackknife to estimate parameter uncertainty...\n \n")
    for (n in 1:N) {
        J <- Y[-n, ]
        Covarsj <- Covars[, -n]
        J <- scaling(J, scale)
        Vp <- 10
        C2p <- p * 3
        muhat <- colMeans(J)
        Jc <- sweep(J, 2, muhat, "-")
        Sj <- (1/nrow(Jc)) * (t(Jc) %*% Jc)
        tol <- epsilon + 1
        v <- 0
        while (tol > epsilon) {
            v <- v + 1
            if (v == 1) {
                Wj <- Wopt
                Sigj <- Sigopt
                Alphaj <- Alphaopt
                uj <- t(Uopt[-n, ])
            }
            M_1 <- solve(t(Wj) %*% Wj + Sigj * diag(q))
            u <- M_1 %*% (t(Wj) %*% t(Jc) + Sigj * (Alphaj %*% 
                Covarsj))
            Sum_Euu <- (nrow(Jc) * Sigj * M_1) + (u %*% t(u))
            Alphaj <- (u %*% t(Covarsj)) %*% solve(Covarsj %*% 
                t(Covarsj))
            Wj <- (t(Jc) %*% t(u)) %*% solve(Sum_Euu)
            YWEu <- sum(diag(Jc %*% Wj %*% u))
            MLESigj <- (nrow(Jc) * sum(diag(Sj)) + sum(diag((t(Wj) %*% 
                Wj) %*% Sum_Euu)) - 2 * YWEu)/(p * nrow(Jc))
            Sigj <- c(((N * p) * MLESigj + C2p)/((N * p) + Vp + 
                2))
            Den <- rep(NA, nrow(J))
            Sigma <- Wj %*% t(Wj) + Sigj * diag(p)
            mumat <- Wj %*% (Alphaj %*% Covarsj) + matrix(colMeans(J), 
                nrow = p, ncol = nrow(J), byrow = FALSE)
            for (i in 1:nrow(J)) {
                Den[i] <- (dmvnorm(J[i, ], mumat[, i], Sigma, 
                  log = TRUE))
            }
            ll[q, v] <- sum(Den)
            converge <- Aitken(ll, lla, v, q, epsilon)
            tol <- converge[[1]]
            lla[q, v] <- converge[[2]]
        }
        Sigstore[n] <- Sigj
        Wstore[, , n] <- Wj
        Alphastore[, , n] <- Alphaj
    }
    se_Alpha <- sqrt((N - 1)^2/N * (apply(Alphastore, c(1, 2), 
        var)))
    se_W <- sqrt((N - 1)^2/N * (apply(Wstore, c(1, 2), var)))
    UpperCI_Alp <- Alphaopt + (qnorm(conflevel + ((1 - conflevel)/2)) * 
        se_Alpha)
    LowerCI_Alp <- Alphaopt - (qnorm(conflevel + ((1 - conflevel)/2)) * 
        se_Alpha)
    UpperCI_W <- Wopt + (qnorm(conflevel + ((1 - conflevel)/2)) * 
        se_W)
    LowerCI_W <- Wopt - (qnorm(conflevel + ((1 - conflevel)/2)) * 
        se_W)
    colnames(LowerCI_Alp) <- paste("LowLim_Beta_", rownames(Covars), 
        sep = "")
    colnames(UpperCI_Alp) <- paste("UpperLim_Beta_", rownames(Covars), 
        sep = "")
    tab1 <- cbind(LowerCI_Alp, UpperCI_Alp)
    for (i in 1:(L + 1)) {
        if (i == 1) {
            CI_Alp <- cbind(tab1[, i], tab1[, (i + L + 1)])
            colnames(CI_Alp) <- colnames(tab1)[c(i, (i + L + 
                1))]
        }
        else {
            tab2 <- cbind(tab1[, i], tab1[, (i + L + 1)])
            colnames(tab2) <- colnames(tab1)[c(i, (i + L + 1))]
            CI_Alp <- cbind(CI_Alp, tab2)
        }
    }
    CI_W <- cbind(LowerCI_W[, 1], UpperCI_W[, 1])
    colnames(CI_W) <- c("LowCI_PC1", "UppCI_PC1")
    ProdciPC1 <- apply(CI_W[, 1:2], 1, prod)
    Signifppmz <- ProdciPC1 > 0
    SignifW <- as.matrix(Wopt[Signifppmz, ])
    nSL <- nrow(SignifW)
    Lower <- as.matrix(LowerCI_W[Signifppmz, ])
    Upper <- as.matrix(UpperCI_W[Signifppmz, ])
    cat("The number of spectral bins with loadings on PC 1 significantly different from 0 is:", 
        nSL, "\n \n")
    grid <- 0.1
    cutoff <- seq(min(abs(SignifW)), max(abs(SignifW)), by = grid)
    nHL <- rep(NA, length(cutoff))
    for (l in 1:length(nHL)) {
        SignifHighppm <- abs(SignifW[, 1]) > cutoff[l]
        SignifHighW <- SignifW[SignifHighppm, ]
        nHL[l] <- sum(SignifHighppm)
    }
    plot(cutoff, nHL, xlab = "Cutoff", ylab = "Number of spectral bins selected", 
        type = "l", cex = 1.2, pch = 21, col = "blue", col.lab = "blue", 
        lwd = 2, main = "Spectral bin selection", col.main = "blue")
    dat <- data.frame(Cutoff = round(cutoff, 2), No.Selected = nHL)
    print(data.frame(dat))
    cat("\n \n")
    number <- nSL
    cutoff <- cutoff[(nHL == number)][1]
    SignifHighppm <- abs(SignifW[, 1]) > cutoff
    SignifHighW <- matrix(SignifW[SignifHighppm, ], ncol = q)
    LowerH <- matrix(Lower[SignifHighppm, ], ncol = q)
    UpperH <- matrix(Upper[SignifHighppm, ], ncol = q)
    barplot2(SignifHighW[, 1], ylim = c(min(LowerH[, 1], 0) - 
        1.5, max(UpperH[, 1], 0) + 1.5), las = 2, width = 0.5, 
        space = 0.5, plot.grid = TRUE, ylab = "PC 1 loadings", 
        xlab = "Spectral regions", names.arg = rownames(SignifW)[SignifHighppm], 
        plot.ci = TRUE, ci.l = LowerH[, 1], ci.u = UpperH[, 1], 
        font.main = 2, col = "red")
    list(q = q, sig = Sigopt, scores = Uopt, loadings = Wopt, 
        SignifW = SignifW, SignifHighW = SignifHighW, LowerCI_W = Lower, 
        UpperCI_W = Upper, coefficients = Alphaopt, coeffCI = CI_Alp, 
        Cutoffs = dat, number = number, cutoff = cutoff, BIC = BIC, 
        AIC = AIC, man.sdev = man.sdev) #SR: introduced man.sdev into output
}


ppcca.metabol.SR <- function (Y, Covars, minq = 1, maxq = 2, scale = "none", epsilon = 0.1, 
    plot.BIC = FALSE, printout = TRUE) 
{
    Y <- as.matrix(Y)
    Covars <- as.matrix(Covars)
    if (missing(Y)) {
        stop("Spectral data are required to fit the PPCCA model.\n")
    }
    if (missing(Covars)) {
        stop("Covariate data are required to fit the PPCCA model.\n ")
    }
    if (nrow(Y) != nrow(Covars)) {
        stop("Spectral data and covariate data should have the same number of rows.\n")
    }
    if (missing(minq)) {
        minq <- 1
    }
    if (missing(maxq)) {
        maxq <- 2
    }
    if (minq > maxq) {
        stop("minq can not be greater than maxq.\n")
    }
    if (maxq > ncol(Y)) {
        stop("maxq can not be greater than the number of variables.\n")
    }
    if (maxq > 10) {
        cat("Warning! Model fitting may become very slow for q > 10.\n\n")
    }
    if (epsilon > 1) {
        cat("Warning! Poor model covergence expected for epsilon > 1.\n")
    }
    if (epsilon < 1e-04) {
        cat("Warning! Model covergence becomes very slow for epsilon < 0.0001.\n")
    }
    V <- 4000
    N <- nrow(Y)
    p <- ncol(Y)
    L <- ncol(Covars)
    Covars <- standardize(Covars)
    Covars <- rbind(rep(1, N), t(Covars))
    Sig_q <- rep(0, maxq)
    W_q <- list()
    Alpha_q <- list()
    U_q <- list()
    AIC <- rep(0, maxq)
    BIC <- rep(0, maxq)
    ll <- matrix(NA, maxq, V)
    lla <- matrix(NA, maxq, V)
    Y <- as.matrix(scaling(Y, type = scale))
    Vp <- 10
    C2p <- p * 3
    muhat <- colMeans(Y)
    Yc <- sweep(Y, 2, muhat, "-")
    S <- (1/nrow(Yc)) * (t(Yc) %*% Yc)
    temp <- eigen(S)
    for (q in minq:maxq) {
        Sig <- abs((1/(p - q)) * sum(temp$val[(q + 1):p]))
        W <- temp$vec[, 1:q]
        scores <- t(solve((t(W) %*% W) + (Sig * diag(q))) %*% 
            t(W) %*% t(Yc))
        Alpha <- matrix(0, q, L + 1)
        for (i in 1:q) {
            if (L == 1) {
                dat <- data.frame(cbind(scores[, i], as.matrix(Covars[2:(L + 
                  1), ])))
            }
            else {
                dat <- data.frame(cbind(scores[, i], t(Covars[2:(L + 
                  1), ])))
            }
            Alpha[i, ] <- glm(dat, family = gaussian)$coef
        }
        tol <- epsilon + 1
        v <- 0
        while (tol > epsilon) {
            v <- v + 1
            M_1 <- solve(t(W) %*% W + Sig * diag(q))
            u <- M_1 %*% (t(W) %*% t(Yc) + Sig * (Alpha %*% Covars))
            Sum_Euu <- (nrow(Yc) * Sig * M_1) + (u %*% t(u))
            Alpha <- (u %*% t(Covars)) %*% solve(Covars %*% t(Covars))
            W <- (t(Yc) %*% t(u)) %*% solve(Sum_Euu)
            YWEu <- sum(diag(Yc %*% W %*% u))
            MLESig <- (nrow(Yc) * sum(diag(S)) + sum(diag((t(W) %*% 
                W) %*% Sum_Euu)) - 2 * YWEu)/(p * nrow(Yc))
            Sig <- c(((N * p) * MLESig + C2p)/((N * p) + Vp + 
                2))
            Den <- rep(NA, nrow(Y))
            Sigma <- W %*% t(W) + (Sig * diag(p))
            mumat <- W %*% (Alpha %*% Covars) + matrix(muhat, 
                nrow = p, ncol = N, byrow = FALSE)
            for (i in 1:nrow(Y)) {
                Den[i] <- (dmvnorm(Y[i, ], mumat[, i], Sigma, 
                  log = TRUE))
            }
            ll[q, v] <- sum(Den)
            converge <- Aitken(ll, lla, v, q, epsilon)
            tol <- converge[[1]]
            lla[q, v] <- converge[[2]]
            if (v == V) {
                cat("Algorithm stopped for q = ", q, ". Maximum number of iterations exceeded.\n\n")
                tol <- epsilon - 1
            }
        }
        if (printout == TRUE) {
            cat("q = ", q, ": PPCCA converged.\n\n")
        }
        params <- (p * q) - (0.5 * q * (q - 1)) + (q * (L + 1)) + 
            1
        AIC[q] <- 2 * ll[q, v] - (2 * params)
        BIC[q] <- 2 * ll[q, v] - params * log(N)
        U_q[[q]] <- u
        Sig_q[q] <- Sig
        W_q[[q]] <- W
        Alpha_q[[q]] <- Alpha
    }
    qopt <- c(minq:maxq)[BIC[minq:maxq] == max(BIC[minq:maxq])]
    Uopt <- t(U_q[[qopt]])
    man.sdev <- apply(Uopt, 2, sd) #SR: introduce man.sdev
    Wopt <- W_q[[qopt]]
    Sigopt <- Sig_q[qopt]
    Alphaopt <- Alpha_q[[qopt]]
    if (plot.BIC == TRUE) {
        plot(minq:maxq, BIC[minq:maxq], type = "b", xlab = "q", 
            ylab = "BIC", col.lab = "blue")
        abline(v = qopt, col = "red", lty = 2)
    }
    list(q = qopt, sig = Sigopt, scores = Uopt, loadings = Wopt, 
        coefficients = Alphaopt, BIC = BIC[minq:maxq], AIC = AIC[minq:maxq], man.sdev = man.sdev) #SR: introduced man.sdev into output
}


  
```

```{r rewrite PPCCA jack-knife function in a way that it won't plot}

ppcca.metabol.jack.SR.no_plot <- function (Y, Covars, minq = 1, maxq = 2, scale = "none", epsilon = 0.1, 
    conflevel = 0.95) 
{
    Y <- as.matrix(Y)
    Covars <- as.matrix(Covars)
    if (missing(Y)) {
        stop("Spectral data are required to fit the PPCCA model.\n")
    }
    if (missing(Covars)) {
        stop("Covariate data are required to fit the PPCCA model.\n ")
    }
    if (nrow(Y) != nrow(Covars)) {
        stop("Spectral data and covariate data should have the same number of rows.\n")
    }
    if (missing(minq)) {
        minq <- 1
    }
    if (missing(maxq)) {
        maxq <- 2
    }
    if (minq > maxq) {
        stop("minq can not be greater than maxq.\n")
    }
    if (maxq > ncol(Y)) {
        stop("maxq can not be greater than the number of variables.\n")
    }
    if (maxq > 10) {
        cat("Warning! Model fitting may become very slow for q > 10.\n\n")
    }
    if (epsilon > 1) {
        cat("Warning! Poor model covergence expected for epsilon > 1.\n")
    }
    if (epsilon < 1e-04) {
        cat("Warning! Model covergence becomes very slow for epsilon < 0.0001.\n")
    }
    Vj <- 40000
    N <- nrow(Y)
    p <- ncol(Y)
    Covars <- as.matrix(Covars, nrow = N, byrow = TRUE)
    L <- ncol(Covars)
    modelfit <- ppcca.metabol.SR(Y, Covars, minq, maxq, scale = scale, 
        epsilon = epsilon, plot.BIC = FALSE, printout = FALSE)
    q <- modelfit$q
    Wj <- Wopt <- modelfit$loadings
    Sigj <- Sigopt <- modelfit$sig
    Alphaj <- Alphaopt <- modelfit$coefficients
    Uopt <- modelfit$scores
    man.sdev <- apply(Uopt, 2, sd) #SR: introduce man.sdev
    BIC <- modelfit$BIC
    AIC <- modelfit$AIC
    Covars <- standardize(Covars)
    Covars <- rbind(rep(1, N), t(Covars))
    if (sum(rownames(Covars) == NULL) == 0) {
        rownames(Covars) <- c(1:(L + 1))
        rownames(Covars)[1] <- "Intercept"
        for (i in 2:(L + 1)) {
            rownames(Covars)[i] <- paste("Covariate", i, sep = "")
        }
    }
    rownames(Covars)[1] <- "Intercept"
    cat("PPCCA fitted to all ", N, " observations. Optimal model has", 
        q, "factors.\n\n")
    Sigstore <- rep(NA, N)
    Wstore <- array(0, c(p, q, N))
    Alphastore <- array(0, c(q, L + 1, nrow(Y)))
    ll <- matrix(0, q, Vj)
    lla <- matrix(0, q, Vj)
    cat("Using the jackknife to estimate parameter uncertainty...\n \n")
    for (n in 1:N) {
        J <- Y[-n, ]
        Covarsj <- Covars[, -n]
        J <- scaling(J, scale)
        Vp <- 10
        C2p <- p * 3
        muhat <- colMeans(J)
        Jc <- sweep(J, 2, muhat, "-")
        Sj <- (1/nrow(Jc)) * (t(Jc) %*% Jc)
        tol <- epsilon + 1
        v <- 0
        while (tol > epsilon) {
            v <- v + 1
            if (v == 1) {
                Wj <- Wopt
                Sigj <- Sigopt
                Alphaj <- Alphaopt
                uj <- t(Uopt[-n, ])
            }
            M_1 <- solve(t(Wj) %*% Wj + Sigj * diag(q))
            u <- M_1 %*% (t(Wj) %*% t(Jc) + Sigj * (Alphaj %*% 
                Covarsj))
            Sum_Euu <- (nrow(Jc) * Sigj * M_1) + (u %*% t(u))
            Alphaj <- (u %*% t(Covarsj)) %*% solve(Covarsj %*% 
                t(Covarsj))
            Wj <- (t(Jc) %*% t(u)) %*% solve(Sum_Euu)
            YWEu <- sum(diag(Jc %*% Wj %*% u))
            MLESigj <- (nrow(Jc) * sum(diag(Sj)) + sum(diag((t(Wj) %*% 
                Wj) %*% Sum_Euu)) - 2 * YWEu)/(p * nrow(Jc))
            Sigj <- c(((N * p) * MLESigj + C2p)/((N * p) + Vp + 
                2))
            Den <- rep(NA, nrow(J))
            Sigma <- Wj %*% t(Wj) + Sigj * diag(p)
            mumat <- Wj %*% (Alphaj %*% Covarsj) + matrix(colMeans(J), 
                nrow = p, ncol = nrow(J), byrow = FALSE)
            for (i in 1:nrow(J)) {
                Den[i] <- (dmvnorm(J[i, ], mumat[, i], Sigma, 
                  log = TRUE))
            }
            ll[q, v] <- sum(Den)
            converge <- Aitken(ll, lla, v, q, epsilon)
            tol <- converge[[1]]
            lla[q, v] <- converge[[2]]
        }
        Sigstore[n] <- Sigj
        Wstore[, , n] <- Wj
        Alphastore[, , n] <- Alphaj
    }
    se_Alpha <- sqrt((N - 1)^2/N * (apply(Alphastore, c(1, 2), 
        var)))
    se_W <- sqrt((N - 1)^2/N * (apply(Wstore, c(1, 2), var)))
    UpperCI_Alp <- Alphaopt + (qnorm(conflevel + ((1 - conflevel)/2)) * 
        se_Alpha)
    LowerCI_Alp <- Alphaopt - (qnorm(conflevel + ((1 - conflevel)/2)) * 
        se_Alpha)
    UpperCI_W <- Wopt + (qnorm(conflevel + ((1 - conflevel)/2)) * 
        se_W)
    LowerCI_W <- Wopt - (qnorm(conflevel + ((1 - conflevel)/2)) * 
        se_W)
    colnames(LowerCI_Alp) <- paste("LowLim_Beta_", rownames(Covars), 
        sep = "")
    colnames(UpperCI_Alp) <- paste("UpperLim_Beta_", rownames(Covars), 
        sep = "")
    tab1 <- cbind(LowerCI_Alp, UpperCI_Alp)
    for (i in 1:(L + 1)) {
        if (i == 1) {
            CI_Alp <- cbind(tab1[, i], tab1[, (i + L + 1)])
            colnames(CI_Alp) <- colnames(tab1)[c(i, (i + L + 
                1))]
        }
        else {
            tab2 <- cbind(tab1[, i], tab1[, (i + L + 1)])
            colnames(tab2) <- colnames(tab1)[c(i, (i + L + 1))]
            CI_Alp <- cbind(CI_Alp, tab2)
        }
    }
    CI_W <- cbind(LowerCI_W[, 1], UpperCI_W[, 1])
    colnames(CI_W) <- c("LowCI_PC1", "UppCI_PC1")
    ProdciPC1 <- apply(CI_W[, 1:2], 1, prod)
    Signifppmz <- ProdciPC1 > 0
    SignifW <- as.matrix(Wopt[Signifppmz, ])
    nSL <- nrow(SignifW)
    Lower <- as.matrix(LowerCI_W[Signifppmz, ])
    Upper <- as.matrix(UpperCI_W[Signifppmz, ])
    cat("The number of spectral bins with loadings on PC 1 significantly different from 0 is:", 
        nSL, "\n \n")
    grid <- 0.1
    cutoff <- seq(min(abs(SignifW)), max(abs(SignifW)), by = grid)
    nHL <- rep(NA, length(cutoff))
    for (l in 1:length(nHL)) {
        SignifHighppm <- abs(SignifW[, 1]) > cutoff[l]
        SignifHighW <- SignifW[SignifHighppm, ]
        nHL[l] <- sum(SignifHighppm)
    }
    plot(cutoff, nHL, xlab = "Cutoff", ylab = "Number of spectral bins selected", 
        type = "l", cex = 1.2, pch = 21, col = "blue", col.lab = "blue", 
        lwd = 2, main = "Spectral bin selection", col.main = "blue")
    dat <- data.frame(Cutoff = round(cutoff, 2), No.Selected = nHL)
    print(data.frame(dat))
    cat("\n \n")
    number <- nSL
    cutoff <- cutoff[(nHL == number)][1]
    SignifHighppm <- abs(SignifW[, 1]) > cutoff
    SignifHighW <- matrix(SignifW[SignifHighppm, ], ncol = q)
    LowerH <- matrix(Lower[SignifHighppm, ], ncol = q)
    UpperH <- matrix(Upper[SignifHighppm, ], ncol = q)
    list(q = q, sig = Sigopt, scores = Uopt, loadings = Wopt, 
        SignifW = SignifW, SignifHighW = SignifHighW, LowerCI_W = Lower, 
        UpperCI_W = Upper, coefficients = Alphaopt, coeffCI = CI_Alp, 
        Cutoffs = dat, number = number, cutoff = cutoff, BIC = BIC, 
        AIC = AIC, man.sdev = man.sdev) #SR: introduced man.sdev into output
}



```

```{r rewrite PPCAjack function without the bar plots}
#also, introduce man.sdev to output value list

ppca.metabol.jack.SR.no_plot <- function (Y, minq = 1, maxq = 2, scale = "none", epsilon = 0.1, 
    conflevel = 0.95) 
{
    if (missing(Y)) {
        stop("Spectral data are required to fit the PPCCA model.\n")
    }
    if (minq > maxq) {
        stop("minq can not be greater than maxq.\n")
    }
    if (maxq > ncol(Y)) {
        stop("maxq can not be greater than the number of variables.\n")
    }
    if (maxq > 30) {
        cat("Warning! Model fitting may become unstable for q > 30.\n\n")
    }
    if (epsilon > 1) {
        cat("Warning! Poor model covergence expected for epsilon > 1.\n")
    }
    if (epsilon < 1e-04) {
        cat("Warning! Model covergence becomes very slow for epsilon < 0.0001.\n")
    }
    Vj <- 5000
    N <- nrow(Y)
    p <- ncol(Y)
    modelfit <- ppca.metabol.SR(Y, minq, maxq, scale = scale, epsilon, 
        plot.BIC = FALSE, printout = FALSE)
    q <- modelfit$q
    Wj <- Wopt <- modelfit$loadings
    Sigj <- Sigopt <- modelfit$sig
    Uopt <- modelfit$scores
    BIC <- modelfit$BIC
    AIC <- modelfit$AIC
    cat("PPCA fitted to all ", N, " observations. Optimal model has", 
        q, "factors.\n \n")
    Sigstore <- rep(NA, N)
    Wstore <- array(0, c(p, q, N))
    ll <- matrix(0, q, Vj)
    lla <- matrix(0, q, Vj)
    
    cat("Using the jackknife to estimate parameter uncertainty...\n \n")
    for (n in 1:N) {
        J <- Y[-n, ]
        J <- scaling(J, scale)
        Vp <- 10
        C2p <- p * 3
        muhat <- colMeans(J)
        Jc <- sweep(J, 2, muhat, "-")
        Sj <- (1/nrow(Jc)) * (t(Jc) %*% Jc)
        tol <- epsilon + 1
        v <- 0
        while (tol > epsilon) {
            v <- v + 1
            if (v == 1) {
                Wj <- Wopt
                Sigj <- Sigopt
                uj <- t(Uopt[-n, ])
            }
            k <- Sj %*% Wj
            M_1 <- solve((t(Wj) %*% Wj + Sigj * diag(q)))
            Wj <- k %*% solve(Sigj * diag(q) + (M_1 %*% t(Wj)) %*% 
                k)
            MLESigj <- (1/p) * sum(diag(Sj - k %*% (M_1 %*% t(Wj))))
            Sigj <- c(((N * p) * MLESigj + C2p)/((N * p) + Vp + 
                2))
            uj <- M_1 %*% (t(Wj) %*% t(Jc))
            ll[q, v] <- sum(dmvnorm(J, muhat, Wj %*% t(Wj) + 
                Sigj * diag(p), log = TRUE))
            converge <- Aitken(ll, lla, v, q, epsilon)
            tol <- converge[[1]]
            lla[q, v] <- converge[[2]]
        }
        Sigstore[n] <- Sigj
        Wstore[, , n] <- Wj
    }
    se_W <- sqrt((N - 1)^2/N * (apply(Wstore, c(1, 2), var)))
    UpperCI_W <- Wopt + (qnorm(conflevel + ((1 - conflevel)/2)) * 
        se_W)
    LowerCI_W <- Wopt - (qnorm(conflevel + ((1 - conflevel)/2)) * 
        se_W)
    CI_W <- cbind(LowerCI_W[, 1], UpperCI_W[, 1])
    colnames(CI_W) <- c("LowCI_PC1", "UppCI_PC1")
    ProdciPC1 <- apply(CI_W[, 1:2], 1, prod)
    Signifppmz <- ProdciPC1 > 0
    SignifW <- Wopt[Signifppmz, , drop = FALSE] #SR: introduced drop = FALSE, bcs otherwise coersion to vector if the chosen dimension, i.e. number of PCs is 1
    nSL <- nrow(SignifW)
      Lower <- as.matrix(LowerCI_W[Signifppmz, ])
    Upper <- as.matrix(UpperCI_W[Signifppmz, ])
    cat("The number of spectral bins with loadings on PC 1 significantly different from 0 is:", 
        nSL, "\n \n")
    grid <- 0.1
    cutoff <- seq(min(abs(SignifW)), max(abs(SignifW)), by = grid)
    nHL <- rep(NA, length(cutoff))
    for (l in 1:length(nHL)) {
        SignifHighppm <- abs(SignifW[, 1]) > cutoff[l]
        SignifHighW <- SignifW[SignifHighppm, ]
        nHL[l] <- sum(SignifHighppm)
    }
    plot(cutoff, nHL, xlab = "Cutoff", ylab = "Number of spectral bins selected", 
        type = "l", cex = 1.2, pch = 21, col = "blue", col.lab = "blue", 
        lwd = 2, main = "Spectral bin selection", col.main = "blue")
    dat <- data.frame(Cutoff = round(cutoff, 2), No.Selected = nHL)
    print(data.frame(dat))
    cat("\n \n")
    number <- nSL
    cutoff <- cutoff[(nHL == number)][1]
    SignifHighppm <- abs(SignifW[, 1]) > cutoff
    SignifHighW <- matrix(SignifW[SignifHighppm, ], ncol = q)
    LowerH <- matrix(Lower[SignifHighppm, ], ncol = q)
    UpperH <- matrix(Upper[SignifHighppm, ], ncol = q)
    man.sdev <- apply(Uopt, 2, sd) #SR: introduce man.sdev
    list(q = q, sig = Sigopt, scores = Uopt, loadings = Wopt, 
        SignifW = SignifW, SignifHighW = SignifHighW, Lower = Lower, 
        Upper = Upper, Cutoffs = dat, number = number, cutoff = cutoff, 
        BIC = BIC, AIC = AIC, man.sdev = man.sdev)
}

```

```{r adapt FELLA buildGraphFromKEGGREST function, so that "organism" isn't needed as input anymore}
#adapt function to make it organism unspecific: use 

buildGraphFromKEGGREST_adapted <-  function (filter.path = NULL) 
{
    categories <- listCategories()
    message("Building through KEGGREST...")
    list.list <- plyr::llply(stats::setNames(categories, categories), #creates a list with entries pathway, module, reaction, enzyme, compound; entries are named vectors with the KEGG identifiers as names and character entries describing the elements.
        function(category) {
                ans <- KEGGREST::keggList(database = category)
            #names(ans) <- FELLA:::sanitise(names(ans), category, organism) #e.g. for "path:hsa05169" removes the "path:", leaving it at "hsa05169"
            names(ans) <- gsub("\\w*[\\w*._%=-]*\\w*[\\w*._%=-]*\\w*:", "", names(ans)) #generalized for all categories and organisms
            ans
        }, .progress = "text")
    map.category <- plyr::ldply(list.list, function(categ) data.frame(id = names(categ), 
        stringsAsFactors = FALSE), .id = "category")
    map.category <- stats::setNames(as.character(map.category$category), 
        map.category$id)
    list.link <- plyr::alply(expand.grid(categories, categories, 
        KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)[lower.tri(matrix(seq_len(25), 
        nrow = 5)), ], 1, function(row) {
        original <- KEGGREST::keggLink(row[1], row[2])
        df <- data.frame(from = gsub("\\w*[\\w*._%=-]*\\w*[\\w*._%=-]*\\w*:", "", original), 
            to = gsub("\\w*[\\w*._%=-]*\\w*[\\w*._%=-]*\\w*:", "", names(original)))
        attr(df, "from") <- as.character(row[1])
        attr(df, "to") <- as.character(row[2])
        df
    }, .progress = "text")
    attributes(list.link) <- NULL
    m.path_ko <- KEGGREST::keggLink("ko", "pathway") %>% 
      gsub("\\w*[\\w*._%=-]*\\w*[\\w*._%=-]*\\w*:", "", .) %>%
        stats::setNames(., gsub("\\w*[\\w*._%=-]*\\w*[\\w*._%=-]*\\w*:", "", names(.)))
    m.mod_ko <- KEGGREST::keggLink("ko", "module") %>% 
      gsub("\\w*[\\w*._%=-]*\\w*[\\w*._%=-]*\\w*:", "", .) %>%
        stats::setNames(., gsub("\\w*[\\w*._%=-]*\\w*[\\w*._%=-]*\\w*:", "", names(.)))
    m.ko_enzyme <- KEGGREST::keggLink("enzyme", "ko") %>% 
      gsub("\\w*[\\w*._%=-]*\\w*[\\w*._%=-]*\\w*:", "", .) %>%
        stats::setNames(., gsub("\\w*[\\w*._%=-]*\\w*[\\w*._%=-]*\\w*:", "", names(.)))
    #keggGene2entrez <- KEGGREST::keggConv("ncbi-geneid", organism) %>% 
     #   gsub(pattern = "(.+:)(\\d+)", replacement = "\\2", x = .) %>% 
      #  split(., names(.))
    
    m.enzyme_ko <- KEGGREST::keggLink("ko", "enzyme") %>% 
      gsub("\\w*[\\w*._%=-]*\\w*[\\w*._%=-]*\\w*:", "", .) %>%
        stats::setNames(., gsub("\\w*[\\w*._%=-]*\\w*[\\w*._%=-]*\\w*:", "", names(.))) %>% 
        split(., names(.), drop = TRUE) %>% plyr::llply(., function(r) sort(r)) %>%
      plyr::llply(., function(r) unname(r))
    con.infere <- list(FELLA:::infere.con2ec(names(list.list$pathway), 
        "pathway", m.path_ko, m.ko_enzyme), FELLA:::infere.con2ec(names(list.list$module), 
        "module", m.mod_ko, m.ko_enzyme))
    df.noinfere <- plyr::ldply(list.link, function(df.piece) {
        a.from <- attr(df.piece, "from")
        a.to <- attr(df.piece, "to")
        if (a.from == "enzyme" & (a.to %in% c("module", "pathway"))) 
            return(NULL)
        return(df.piece)
    }, .id = NULL)
    df.infere <- plyr::ldply(con.infere, function(df.piece) {
        a.from <- attr(df.piece, "from")
        a.to <- attr(df.piece, "to")
        return(df.piece)
    })
    matrix.adjacency <- as.matrix(rbind(df.noinfere, df.infere))
    message("Done.")
    message("Building graph...")
    g.raw <- igraph::simplify(igraph:::graph.edgelist(matrix.adjacency, 
        directed = TRUE))
    igraph:::V(g.raw)$com <- match(map.category[igraph:::V(g.raw)$name], categories)
    g.raw <- igraph:::delete.vertices(g.raw, which(is.na(igraph:::V(g.raw)$com)))
    g.raw <- igraph:::delete.vertices(g.raw, which((igraph:::V(g.raw)$com == 3) & 
        !(igraph:::V(g.raw)$name %in% df.infere$from)))
    g.raw <- igraph:::permute.vertices(g.raw, order(order(igraph:::V(g.raw)$com, 
        igraph:::V(g.raw)$name)))
    tmp <- igraph:::get.edges(g.raw, igraph:::E(g.raw))
    igraph:::E(g.raw)$weight <- abs(igraph:::V(g.raw)$com[tmp[, 1]] - igraph:::V(g.raw)$com[tmp[, 
        2]])
    g.raw <- (setdiff(which(igraph:::V(g.raw)$com == 4), igraph:::get.edges(g.raw, 
        igraph:::E(g.raw)[igraph:::E(g.raw)$weight == 3])[, 1]) %>% igraph:::delete.vertices(graph = g.raw, 
        .))
    g.raw <- (setdiff(which(igraph:::V(g.raw)$com == 5), igraph:::get.edges(g.raw, 
        igraph:::E(g.raw)[igraph:::E(g.raw)$weight == 1])[, 1]) %>% igraph:::delete.vertices(graph = g.raw, 
        .))
    if (!is.null(filter.path)) {
        names.path <- igraph:::V(g.raw)[igraph:::V(g.raw)$com == 1]$name
        filter.out <- lapply(filter.path, function(p) {
            which(grepl(p, names.path))
        })
        names.out <- names.path[unique(unlist(filter.out))]
        message(paste0("Filtering ", length(names.out), " pathways."))
        g.raw <- igraph:::delete.vertices(g.raw, names.out)
    }
    g.raw <- FELLA:::largestcc(g.raw)
    message("Done.")
    message("Pruning graph...")
    edges.split <- split(seq_len(igraph:::ecount(g.raw)), igraph:::E(g.raw)$weight)
    message(paste0("Current weight: 1 out of 4..."))
    g.curated <- igraph:::subgraph.edges(graph = g.raw, eids = edges.split[[1]], 
        delete.vertices = FALSE)
    for (w in names(edges.split)[-1]) {
        current.w <- as.numeric(w)
        message(paste0("Current weight: ", w, " out of 4..."))
        dist.matrix <- igraph:::distances(g.curated, mode = "out")
        list.edges <- edges.split[[w]]
        list.ends <- igraph:::ends(g.raw, list.edges)
        new.edges <- dist.matrix[list.ends] > igraph:::E(g.raw)$weight[list.edges]
        g.curated <- igraph:::add.edges(graph = g.curated, edges = t(list.ends[new.edges, 
            ]), attr = list(weight = igraph:::E(g.raw)[list.edges[new.edges]]$weight))
    }
    igraph:::E(g.curated)$weight <- 1/igraph:::E(g.curated)$weight
    tmp <- list.list
    names(tmp) <- NULL
    tmp <- unlist(tmp)
    igraph:::V(g.curated)$NAME <- strsplit(tmp[igraph:::V(g.curated)$name], split = "; ")
    igraph:::V(g.curated)$entrez <- m.enzyme_ko[igraph:::V(g.curated)$name]
    message("Done.")
    keggdata.graph <- g.curated
    return(keggdata.graph)
}

```


