---
title: "Alpha diversity"
output:
  html_document:
    df_print: paged
---


```{r, echo=FALSE, message=FALSE, warning=FALSE, results="asis"}
knitr::opts_chunk$set(
  message = FALSE, error = FALSE, warning = FALSE, 
  fig.width = 8, fig.height = 6,
  fig.path = "./figs/alpha_diversity/", 
  dev='png') 
```

```{r setup, include=FALSE}
library("phyloseq")
library("RColorBrewer")
library("tidyverse")

datadir <- "../../data/"
curdir <- getwd()
theme_set(theme_bw())
theme_update(text = element_text(20))

theme_subplot <- theme(
      legend.position = "none",
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(),
      panel.background = element_rect(fill = "transparent",colour = NA),
      plot.background = element_rect(fill = "transparent",colour = NA)
    )

abx_intv_cols <- c("PreAbx" = "grey60", "MidAbx" = "#E41A1C", 
                   "PostAbx" = "#00BFC4", "UnpAbx" = "Purple")
diet_intv_cols <- c("PreDiet" = "grey60", "MidDiet" = "#FD8D3C", 
                    "PostDiet" = "#4DAF4A")
cc_intv_cols <- c("PreCC" = "grey60", "PostCC" = "#7A0177") 

intv_cols <- c(abx_intv_cols, diet_intv_cols, cc_intv_cols, "NoInterv" = "grey60")
```

# Load Data

```{r}
# File generated in /perturbation_16s/analysis/analysis_summer2019/generate_phyloseq.rmd
psSubj <- readRDS("../../data/16S/phyloseq/perturb_physeq_participants_decontam_15Jul19.rds")
psSubj
# otu_table()   OTU Table:         [ 2425 taxa and 4402 samples ]
# sample_data() Sample Data:       [ 4402 samples by 40 sample variables ]
SMP <- data.frame(sample_data(psSubj))
SUBJ <- SMP %>% select(Subject, Age:BirthYear) %>% distinct()

alphaDiversity <- readRDS("output/alphaDiversity.rds")
```

# Alpha Diversity

```{r, eval = FALSE}
alphaDiversity <- estimate_richness(
  psSubj, split = TRUE, measures = c("Observed", "Shannon", "InvSimpson"))

prunedTree <- prune.sample(t(as(otu_table(psSubj), "matrix")), phy_tree(psSubj))
phyloDiver <- picante::pd(t(as(otu_table(psSubj), "matrix")),prunedTree)


alphaDiversity <- alphaDiversity %>%
  rownames_to_column("Meas_ID") %>%
  left_join(phyloDiver %>% rownames_to_column("Meas_ID") %>% select(-SR)) %>%
  left_join(SMP)

saveRDS(alphaDiversity, file = "output/alphaDiversity.rds")
```


# Plot richness trends


```{r}
df <- alphaDiversity %>% 
  select(-Interval) %>%
  gather(key = "diversity_metric", value = "value", Observed:PD) %>%
  mutate(
    Abx_Interval = factor(Abx_Interval, level = names(abx_intv_cols)),
    Diet_Interval = factor(Diet_Interval, level = names(diet_intv_cols)),
    CC_Interval = factor(CC_Interval, level = names(cc_intv_cols)),
    diversity_metric = factor(diversity_metric, levels = c("Observed", "Shannon","InvSimpson", "PD"))) %>%
  mutate_at(.vars = vars(contains("_Interval")), .funs = as.character) %>%
  gather(key = "perturb_relday", value = "RelDay", contains("_RelDay")) %>%
  gather(key = "perturb_interval", value = "Interval", contains("_Interval")) %>%
  mutate(perturb_relday = gsub("_RelDay", "", perturb_relday), 
         perturb_interval = gsub("_Interval", "", perturb_interval)) %>%
  filter(perturb_relday == perturb_interval, !is.na(RelDay))
```


```{r alphaDiver-abx, fig.width=10, fig.height=10}
df %>% 
  arrange(diversity_metric, perturb_interval, Subject, RelDay) %>%
  ggplot(
    aes(x = RelDay, y = value, 
        group = Subject, color = Interval)) +
  geom_line(aes(group = Subject), alpha = 0.3, lwd = 0.5) + 
  geom_point(alpha = 0.3, size = 0.5) + 
  scale_color_manual(values = intv_cols) + 
  theme(legend.position = "bottom") + 
  guides(colour = guide_legend(override.aes = list(size=3))) +
  facet_grid(diversity_metric ~ perturb_interval, scales = "free") +
  xlab("Days from perturbation") +
  ylab("Alpha diversity") 
```

```{r alphaDiver-abx-smooth, fig.width=10, fig.height=10}
df %>% 
  arrange(diversity_metric, perturb_interval, Subject, RelDay) %>%
  ggplot(aes(x = RelDay, y = value)) +
  geom_line(aes(group = Subject,color = Interval), alpha = 0.3, lwd = 0.5) + 
  geom_point(aes(color = Interval), alpha = 0.3, size = 0.5) + 
  geom_smooth(color = "navy", size = 1) +
  scale_color_manual(values = intv_cols) + 
  theme(legend.position = "bottom") + 
  guides(colour = guide_legend(override.aes = list(size=3))) +
  facet_grid(diversity_metric ~ perturb_interval, scales = "free") +
  xlab("Days from perturbation") +
  ylab("Alpha diversity") +
  xlim(-60, 60)
```


```{r alphaDiver-abx-zoom-smooth, fig.width=10, fig.height=10}
df %>% 
  arrange(diversity_metric, perturb_interval, Subject, RelDay) %>%
  ggplot(
    aes(x = RelDay, y = value)) +
  geom_line(aes(group = Subject, color = Interval), alpha = 0.3, lwd = 0.5) + 
  geom_point(aes(color = Interval), alpha = 0.5, size = 0.5) + 
  geom_smooth(color = "navy", size = 1) +
  scale_color_manual(values = intv_cols) + 
  theme(legend.position = "bottom") + 
  guides(colour = guide_legend(override.aes = list(size=3))) +
  facet_grid(diversity_metric ~ perturb_interval, scales = "free") +
  xlab("Days from perturbation") +
  ylab("Alpha diversity") + 
  xlim(-30, 30)
```





```{r}
sessionInfo()
```

