---
title: "Tree Discriminant Analysis"
output:
  html_document:
    df_print: paged
---


```{r, echo=FALSE, message=FALSE, warning=FALSE, results="asis"}
knitr::opts_chunk$set(
  message = FALSE, error = FALSE, warning = FALSE, 
  fig.width = 8, fig.height = 6,
  fig.path = "./figs/treeDA_and_agpca/", 
  dev='png') 
```

```{r setup, include=FALSE}
library("phyloseq")
library("RColorBrewer")
library("tidyverse")
library("treeDA")
library("adaptiveGPCA")

datadir <- "../../data/"
curdir <- getwd()
theme_set(theme_bw())
theme_update(text = element_text(20))

theme_subplot <- theme(
      legend.position = "none",
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(),
      panel.background = element_rect(fill = "transparent",colour = NA),
      plot.background = element_rect(fill = "transparent",colour = NA)
    )

abx_intv_cols <- c("PreAbx" = "grey60", "MidAbx" = "#E41A1C", 
                   "PostAbx" = "#00BFC4", "UnpAbx" = "Purple")
diet_intv_cols <- c("PreDiet" = "grey60", "MidDiet" = "#FD8D3C", 
                    "PostDiet" = "#4DAF4A")
cc_intv_cols <- c("PreCC" = "grey60", "PostCC" = "#7A0177") 

intv_cols <- c(abx_intv_cols, diet_intv_cols, cc_intv_cols, "NoInterv" = "grey60")
```

```{r}
# Filter taxa that occurs at minTaxaSum in at least minNoSubj subjects
filter_taxa <- function(ps, minTaxaSum=10, minTaxaPrev=3, minNoSubj=3) {
  ASVsum <- data.frame(t(as(otu_table(ps), "matrix"))) %>%
    mutate(Subject = ps@sam_data$Subject) %>%
    group_by(Subject) %>%
    summarise_all(sum)
  ASVprev <- data.frame(t(as(otu_table(ps), "matrix")) > 0) %>%
    mutate(Subject = ps@sam_data$Subject) %>%
    group_by(Subject) %>%
    summarise_all(sum)
  
  keepASV <- data.frame(
    Seq_ID = colnames(ASVsum),
    abundant = colSums(ASVsum >= minTaxaSum) >= minNoSubj, 
    prevalent = colSums(ASVprev >= minTaxaPrev) >= minNoSubj) %>%
    filter(abundant, prevalent)
  
  ps <- prune_taxa(taxa_names(ps) %in% keepASV$Seq_ID, ps)
  return(ps)
}

plot_coefficients <- function (out.treeda, 
                               color = NULL,
                               remove.bl = TRUE, 
                               ladderize = TRUE, 
                               tree.height = 2) 
{
  predictor.names <- colnames(out.treeda$input$predictors)
  tr = out.treeda$input$tree
  if (remove.bl) {
    tr$edge.length = rep(1, length(tr$edge.length))
  }
  tree.plot = plot_tree(tr, ladderize = ladderize) + coord_flip() + 
    scale_x_reverse()
  leaf.position = get_leaf_position(out.treeda$input$tree, 
                                    ladderize = ladderize)$otu.pos
  coef = as(out.treeda$leafCoefficients$beta, "matrix")
  colnames(coef) = paste("Axis", 1:ncol(coef))
  df = data.frame(coef, leaf.position)
  df = reshape2::melt(df, id.vars = "leaf.position")
  df$predictor.names <- predictor.names 
  coef.plot = ggplot(df) +
    facet_grid(variable ~ .) + 
    ylab("Coefficient value") + 
    theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), 
          axis.title.x = element_blank(), panel.grid.major.x = element_blank(), 
          panel.grid.minor.x = element_blank())
  if(!is.null(color)) {
    coef.plot <- coef.plot + 
      geom_point(aes(x = leaf.position, y = value, color = color))
  } else {
    coef.plot <- coef.plot + geom_point(aes(x = leaf.position, y = value))
  }
  p = combine_plot_and_tree(coef.plot, tree.plot, tree.height = tree.height, 
                            print = FALSE)
  grid::grid.draw(p)
  invisible(p)
  return(list("df" = df, "coef.plot" = coef.plot, "tree.plot" = tree.plot))
}

```

# Load Data

```{r}
# File generated in /perturbation_16s/analysis/analysis_summer2019/generate_phyloseq.rmd
psSubj <- readRDS("../../data/16S/phyloseq/perturb_physeq_participants_decontam_15Jul19.rds")
psSubj
# otu_table()   OTU Table:         [ 2425 taxa and 4402 samples ]
# sample_data() Sample Data:       [ 4402 samples by 40 sample variables ]
SMP <- data.frame(sample_data(psSubj))
SUBJ <- SMP %>% select(Subject, Age:BirthYear) %>% distinct()
TAXTAB <- data.frame(as(tax_table(psSubj), "matrix")) %>%
  rownames_to_column("Seq_ID") %>%
  select(-Seq) %>%
  mutate(
    OrgName.RDP = paste(Genus, Species),
    OrgName.Silva = paste(GenusSilva, SpeciesSilva),
    OrgName = ifelse(grepl("NA", OrgName.RDP) & !grepl("NA", OrgName.RDP),
                     OrgName.Silva, OrgName.RDP),
    OrgName = ifelse(OrgName == "NA NA", "NA", OrgName),
    OrgName = paste0(Seq_ID, ": ", OrgName)) %>%
  select(1:8, OrgName) 
```

```{r}
load("output/treeDA_and_agpca.rda")
```

## Process data

```{r}
dds <- phyloseq_to_deseq2(psSubj, design = ~ 1)
dds <- DESeq2::estimateSizeFactors(dds, type = "poscounts")
norm_counts <- DESeq2::counts(dds, normalized = TRUE)
psSubj.norm <- psSubj
otu_table(psSubj.norm) <- otu_table(norm_counts, taxa_are_rows = TRUE)
psSubj.norm
```



# Tree Discriminant Analysis

## Response to Antibiotics

```{r}
abx <- subset_samples(psSubj.norm, Abx_RelDay >= -50)
abx <- subset_taxa(abx, taxa_sums(abx) > 0)
abx

(replicated <- data.frame(sample_data(abx)) %>% 
  group_by(Subject, Group, Interval, Abx_RelDay) %>%
  mutate(n = n()) %>%
  ungroup() %>% filter(n > 1))
```

```{r}
# Remove replicated samples
sample_sums(abx)[replicated$Meas_ID]

#  M2242  M2243  M7869  M7886 
# 109520  88834  74697  74873 

# we retain a replicate with higher sample depth:

abx <- subset_samples(abx, !Meas_ID %in% c("M2243", "M7869"))
abx
#otu_table()   OTU Table:         [ 2339 taxa and 1418 samples ] 
```

Response intervals

```{r}
sample_data(abx)$ImmediateEff <- ifelse(
  sample_data(abx)$Abx_RelDay %in% seq(-3, 0), "ImmPre", 
  ifelse(sample_data(abx)$Abx_RelDay %in% seq(3, 6), "ImmPost", NA)) 
```

```{r}
sample_data(abx)$LongtermEff <- ifelse(
  sample_data(abx)$Abx_RelDay %in% seq(-30,0), "PrePert", 
  ifelse(sample_data(abx)$Abx_RelDay %in% seq(15, 45), "PostPert", NA)) 
```

```{r exp-design, fig.width=8, fig.height=8}
abx_SMP <- data.frame(sample_data(abx)) %>%
  mutate(Samp_Date = as.Date(Samp_Date))

new_intv_levs <- unique(abx_SMP$Interval)
colors <- colorRampPalette(brewer.pal(8, "Dark2"))(length(new_intv_levs)-2)
colors <- c("grey57", "red", colors)
names(colors) <- c("NoInterv", "MidAbx", "PostDiet_PreAbx", 
                   "PostDiet_PostAbx", "PostDiet_PostCC_PreAbx", 
                   "PostDiet_PostCC_PostAbx", "PostAbx", "UnpAbx")
ggplot(
  abx_SMP, aes(y = Subject, x = Abx_RelDay)) +
  geom_point(
      aes(color = Interval, fill = Interval), 
      pch = 124, size = 3) +
    facet_grid(Group ~ ., scales = "free", space = "free") +
    scale_color_manual(values = colors) +
    theme(legend.direction = "horizontal", legend.box = "vertical",
          strip.text.y = element_text(angle=270, size = 10)) +
    guides(color = guide_legend(nrow = 3 , override.aes = list(size=3, pch = 16)))
```





## Two classes contrast

### Immediate Effect

```{r}
abx_immEff <- subset_samples(abx, ImmediateEff %in%  c("ImmPre", "ImmPost")) 
abx_immEff <- filter_taxa(abx_immEff, minTaxaSum=10, minTaxaPrev=3, minNoSubj=3)
abx_immEff
```

```{r}
table(sample_data(abx_immEff)$ImmediateEff)
```



```{r, eval = FALSE}
abxImmEff.treeda = treeDA::treeda(
  response = sample_data(abx_immEff)$ImmediateEff,
  predictors = asinh(t(otu_table(abx_immEff))),
  tree = phy_tree(abx_immEff), 
  p = 50, scale = FALSE)

save(list = c("abxImmEff.treeda"), file = "output/treeDA_and_agpca.rda")
```

```{r}
abxImmEff.treeda
```

```{r}
ggplot(data.frame(sample_data(abx_immEff), 
                  projections = abxImmEff.treeda$projections)) +
  geom_point(aes(x = Subject, y = projections, color = ImmediateEff)) +
  theme(axis.text.x = element_text(angle = 90))
```


```{r}
nTaxa <- 10; thresh <- 1e-3
beta <- as.numeric(abxImmEff.treeda$leafCoefficients$beta)
taxtab.abxImmEff <- data.frame(
  beta = beta,
  Seq_ID = rownames(as(tax_table(abx_immEff), "matrix")), 
  stringsAsFactors = FALSE) %>%
  left_join(TAXTAB)

freq_family <- taxtab.abxImmEff %>%
  group_by(Family) %>%
  summarise(Freq = n()) %>%
  filter(!is.na(Family)) %>%
  arrange(desc(Freq))

family_levels <- unique(c(
  as.character(freq_family$Family[1:nTaxa]),
  as.character(taxtab.abxImmEff$Family[abs(beta) > thresh])))[1:nTaxa]

taxtab.abxImmEff$family <- factor(taxtab.abxImmEff$Family, levels = family_levels)
```


```{r  abx-treeDA-immEff-tree, fig.width=12, fig.height=6}
plts_immeff_abx <- plot_coefficients(abxImmEff.treeda, color = taxtab.abxImmEff$family)
combine_plot_and_tree(plts_immeff_abx$coef.plot, plts_immeff_abx$tree.plot, tree.height = 1)
```





```{r  abx-treeDA-immEff-labs, fig.width=12, fig.height=6}
df <- plts_immeff_abx$df %>% 
  left_join(TAXTAB, by =c("predictor.names" = "Seq_ID")) %>%
  mutate(
        Family = taxtab.abxImmEff$family,
        Species = ifelse(is.na(Species), "", as.character(Species)),
        Genus = ifelse(is.na(Genus), "", as.character(Genus)),
        org.name = paste(Genus, Species),
        Seq_ID = predictor.names,
        predictor.names = ifelse(org.name == " ", predictor.names, org.name)) %>%
  filter(abs(value) > 0.01) 

df <- df[!duplicated(df[, c("value", "predictor.names")]),]

coef.plot <- plts_immeff_abx$coef.plot +
  ggrepel::geom_text_repel(
    data = df, size = 4, fontface = "bold",
    aes(x = leaf.position, y = value, label = predictor.names, color = Family)
  )
coef.plot
```


```{r}
df %>% select(value, Seq_ID, Family:OrgName) %>% 
  arrange(value)
```

```{r}
load( file = "output/fpca_clust_res_abx_norm.rda")

abx2plot.fclust <- abx_fclust_subjFit %>%
  left_join(TAXTAB, by = c("Feature_ID" = "Seq_ID")) %>%
  group_by(Feature_ID) %>%
  mutate(
    n_cluster1 = sum(Cluster == 1),
    n_cluster2 = sum(Cluster == 2),
    majorityCluster = ifelse(n_cluster1 > n_cluster2, 1, 2)
  ) %>% 
  ungroup() %>%
  mutate(
    Subject_Cluster = ifelse(Cluster == majorityCluster, "Majority", "Minority")) 


abx2plot <- abx.rsv.subset %>% 
  left_join(
    abx2plot.fclust %>% 
      select(-value, -time) %>%
      distinct() %>%
      dplyr::rename(Seq_ID = Feature_ID,  Subject = Replicate_ID) 
  ) 

```

```{r immEff-abx, fig.width=12, fig.height=10}
seq_to_plot <- df$Seq_ID[1:20]
abx2plot.fclust %>%
    filter(Feature_ID %in% seq_to_plot) %>%
ggplot(aes(x = time, y = value, color = Subject_Cluster)) +
  geom_line(
    aes(group = Replicate_ID),
    alpha = 0.3, size = 0.5
  ) +
  geom_smooth(se = FALSE) +
  geom_point(
    data = abx2plot %>%   filter(Seq_ID %in% seq_to_plot),
    aes(x = Abx_RelDay, y = abundance),
    size = 0.3, alpha = 0.5
  ) +
  geom_vline(xintercept = 0, lwd = 1, color = "orange") +
  geom_vline(xintercept = 4, lwd = 1, color = "orange") +
  geom_line(
    data = abx_fclust_mu %>% 
      filter(Feature_ID %in% seq_to_plot) %>% 
      left_join(TAXTAB, by = c("Feature_ID" = "Seq_ID")),
    color = "red", size = 1
  ) +
  scale_color_manual(values = c( "grey17", "deepskyblue2")) +
  facet_wrap(~ OrgName, scales = "free", ncol = 4) +
  ylab("Variance stabilized counts, asinh(cnt)") +
  theme(strip.text = element_text(family="Helvetica-Narrow", size = 10)) +
  scale_x_continuous(name = "Days from initial antibiotic dose",
                     breaks = seq(-40, 120, 20), labels =  seq(-40, 120, 20),
                 limits = c(NA, NA)) 
```

```{r abx-treeDA-immEff-tree-labs, fig.width=12, fig.height=8}
combine_plot_and_tree(coef.plot, plts$tree.plot, tree.height = 1)
```


### Long Term Effect



```{r}
abx_longEff <- subset_samples(abx, LongtermEff %in%  c("PrePert", "PostPert")) 
abx_longEff <- filter_taxa(abx_longEff, minTaxaSum=10, minTaxaPrev=3, minNoSubj=3)
abx_longEff
```

```{r}
table(sample_data(abx_longEff)$LongtermEff)
```



```{r, eval = FALSE}
abxlongEff.treeda = treeDA::treeda(
  response = sample_data(abx_longEff)$LongtermEff,
  predictors = asinh(t(otu_table(abx_longEff))),
  tree = phy_tree(abx_longEff), 
  p = 50, scale = FALSE)

save(list = c("abxImmEff.treeda", "abxlongEff.treeda"), file = "output/treeDA_and_agpca.rda")
```

```{r}
abxlongEff.treeda
```

```{r}
ggplot(data.frame(sample_data(abx_longEff), 
                  projections = abxlongEff.treeda$projections)) +
  geom_point(aes(x = Subject, y = projections, color = LongtermEff)) +
  theme(axis.text.x = element_text(angle = 90))
```


```{r}
nTaxa <- 10; thresh <- 1e-3
beta <- as.numeric(abxlongEff.treeda$leafCoefficients$beta)
taxtab.abxlongEff <- data.frame(
  beta = beta,
  Seq_ID = rownames(as(tax_table(abx_longEff), "matrix")), 
  stringsAsFactors = FALSE) %>%
  left_join(TAXTAB)

freq_family <- taxtab.abxlongEff %>%
  group_by(Family) %>%
  summarise(Freq = n()) %>%
  filter(!is.na(Family)) %>%
  arrange(desc(Freq))

family_levels <- unique(c(
  as.character(freq_family$Family[1:nTaxa]),
  as.character(taxtab.abxlongEff$Family[abs(beta) > thresh])))[1:nTaxa]

taxtab.abxlongEff$family <- factor(taxtab.abxlongEff$Family, levels = family_levels)
```


```{r abx-treeDA-longEff-tree, fig.width=12, fig.height=7.5}
plts_longEff_abx <- plot_coefficients(abxlongEff.treeda, color = taxtab.abxlongEff$family)
combine_plot_and_tree(plts_longEff_abx$coef.plot, plts_longEff_abx$tree.plot, tree.height = 1)
```




```{r abx-treeDA-longEff-labs, fig.width=12, fig.height=6}
df <- plts_longEff_abx$df %>% 
  left_join(TAXTAB, by =c("predictor.names" = "Seq_ID")) %>%
  mutate(
        Family = taxtab.abxlongEff$family,
        Species = ifelse(is.na(Species), "", as.character(Species)),
        Genus = ifelse(is.na(Genus), "", as.character(Genus)),
        org.name = paste(Genus, Species),
        Seq_ID = predictor.names,
        predictor.names = ifelse(org.name == " ", predictor.names, org.name)) %>%
  filter(abs(value) > 0.015) 

df <- df[!duplicated(df[, c("value", "predictor.names")]),]

coef.plot <- plts_longEff_abx$coef.plot +
  ggrepel::geom_text_repel(
    data = df, size = 4, fontface = "bold",
    aes(x = leaf.position, y = value, label = predictor.names, color = Family)
  )
coef.plot
```

```{r abx-treeDA-longEff-tree-labs,fig.width=12, fig.height=8}
combine_plot_and_tree(coef.plot, plts_longEff_abx$tree.plot, tree.height = 1)
```



```{r}
df %>% select(value, Seq_ID, Family:OrgName)
```


```{r longEff-abx, fig.width=12, fig.height=10}
seq_to_plot <- df$Seq_ID[1:20]
abx2plot.fclust %>%
    filter(Feature_ID %in% seq_to_plot) %>%
ggplot(aes(x = time, y = value, color = Subject_Cluster)) +
  geom_line(
    aes(group = Replicate_ID),
    alpha = 0.3, size = 0.5
  ) +
  geom_smooth(se = FALSE) +
  geom_point(
    data = abx2plot %>%   filter(Seq_ID %in% seq_to_plot),
    aes(x = Abx_RelDay, y = abundance),
    size = 0.3, alpha = 0.5
  ) +
  geom_vline(xintercept = 0, lwd = 1, color = "orange") +
  geom_vline(xintercept = 4, lwd = 1, color = "orange") +
  geom_line(
    data = abx_fclust_mu %>% 
      filter(Feature_ID %in% seq_to_plot) %>% 
      left_join(TAXTAB, by = c("Feature_ID" = "Seq_ID")),
    color = "red", size = 1
  ) +
  scale_color_manual(values = c( "grey17", "deepskyblue2")) +
  facet_wrap(~ OrgName, scales = "free", ncol = 4) +
  ylab("Variance stabilized counts, asinh(cnt)") +
  theme(strip.text = element_text(family="Helvetica-Narrow", size = 10)) +
  scale_x_continuous(name = "Days from initial antibiotic dose",
                     breaks = seq(-40, 120, 20), labels =  seq(-40, 120, 20),
                 limits = c(NA, NA)) 
```



## Response to Diet

```{r}
diet <- subset_samples(psSubj.norm, Diet_RelDay >= -30 & Diet_RelDay <= 45)
diet <- subset_taxa(diet, taxa_sums(diet) > 0)
diet

(replicated <- data.frame(sample_data(diet)) %>% 
  group_by(Subject, Group, Interval, Diet_RelDay) %>%
  mutate(n = n()) %>%
  ungroup() %>% filter(n > 1))
```

```{r}
# Remove replicated samples
sample_sums(diet)[replicated$Meas_ID]

# M7869 M7886 
# 74697 74873 

# we retain a replicate with higher sample depth:

diet <- subset_samples(diet, !Meas_ID %in% c("M7869"))
diet
#otu_table()   OTU Table:         [ 2284 taxa and 1055 samples ]

```

Response intervals

```{r}
sample_data(diet)$ImmediateEff <- ifelse(
  sample_data(diet)$Diet_RelDay %in% seq(-3, 0), "ImmPre", 
  ifelse(sample_data(diet)$Diet_RelDay %in% seq(3, 6), "ImmPost", NA)) 
```

```{r}
sample_data(diet)$LongtermEff <- ifelse(
  sample_data(diet)$Diet_RelDay %in% seq(-30,0), "PrePert", 
  ifelse(sample_data(diet)$Diet_RelDay %in% seq(15, 45), "PostPert", NA)) 
```



```{r exp-design, fig.width=8, fig.height=8}
diet_SMP <- data.frame(diet@sam_data) %>%
  mutate(Samp_Date = as.Date(Samp_Date))

new_intv_levs <- unique(diet_SMP$Interval)
colors <- colorRampPalette(brewer.pal(8, "Dark2"))(length(new_intv_levs)-2)
colors <- c("grey57", "red", colors)
names(colors) <- c("NoInterv", "MidDiet", "PostDiet_PreAbx", "PostDiet_PreCC",
                   "PostDiet_PreCC_PreAbx")
ggplot(
  diet_SMP, aes(y = Subject, x = Diet_RelDay)) +
  geom_point(
      aes(color = Interval, fill = Interval), 
      pch = 124, size = 3) +
    facet_grid(Group ~ ., scales = "free", space = "free") +
    scale_color_manual(values = colors) +
    theme(legend.direction = "horizontal", legend.box = "vertical",
          strip.text.y = element_text(angle=270, size = 10)) +
    guides(color = guide_legend(nrow = 2 , override.aes = list(size=3, pch = 16)))
```

## Two classes contrast

### Immediate Effect

```{r}
diet_immEff <- subset_samples(diet, ImmediateEff %in%  c("ImmPre", "ImmPost")) 
diet_immEff <- filter_taxa(diet_immEff, minTaxaSum=10, minTaxaPrev=3, minNoSubj=3)
diet_immEff
```

```{r}
table(sample_data(diet_immEff)$ImmediateEff)
```




```{r, eval = FALSE}
dietImmEff.treeda = treeDA::treeda(
  response = sample_data(diet_immEff)$ImmediateEff,
  predictors = asinh(t(otu_table(diet_immEff))),
  tree = phy_tree(diet_immEff), 
  p = 50, scale = FALSE)

save(list = c("abxImmEff.treeda", "abxlongEff.treeda", "dietImmEff.treeda"), 
     file = "output/treeDA_and_agpca.rda")
```

```{r}
dietImmEff.treeda
```



```{r}
ggplot(data.frame(sample_data(diet_immEff), 
                  projections = dietImmEff.treeda$projections)) +
  geom_point(aes(x = Subject, y = projections, color = ImmediateEff)) +
  theme(axis.text.x = element_text(angle = 90))
```


```{r}
nTaxa <- 10; thresh <- 1e-3
beta <- as.numeric(dietImmEff.treeda$leafCoefficients$beta)
taxtab.dietImmEff <- data.frame(
  beta = beta,
  Seq_ID = rownames(as(tax_table(diet_immEff), "matrix")), 
  stringsAsFactors = FALSE) %>%
  left_join(TAXTAB)

freq_family <- taxtab.dietImmEff %>%
  group_by(Family) %>%
  summarise(Freq = n()) %>%
  filter(!is.na(Family)) %>%
  arrange(desc(Freq))

family_levels <- unique(c(
  as.character(freq_family$Family[1:nTaxa]),
  as.character(taxtab.dietImmEff$Family[abs(beta) > thresh])))[1:nTaxa]

taxtab.dietImmEff$family <- factor(taxtab.dietImmEff$Family, levels = family_levels)
```


```{r diet-treeDA-immEff-tree, fig.width=12, fig.height=6}
plts_immEff_diet <- plot_coefficients(dietImmEff.treeda, color = taxtab.dietImmEff$family)
combine_plot_and_tree(plts_immEff_diet$coef.plot, plts_immEff_diet$tree.plot, tree.height = 1)
```





```{r diet-treeDA-immEff-labs, fig.width=12, fig.height=6}
df <- plts_immEff_diet$df %>% 
  left_join(TAXTAB, by =c("predictor.names" = "Seq_ID")) %>%
  mutate(
        Family = taxtab.dietImmEff$family,
        Species = ifelse(is.na(Species), "", as.character(Species)),
        Genus = ifelse(is.na(Genus), "", as.character(Genus)),
        org.name = paste(Genus, Species),
        Seq_ID = predictor.names,
        predictor.names = ifelse(org.name == " ", predictor.names, org.name)) %>%
  filter(abs(value) > 0.015) 

df <- df[!duplicated(df[, c("value", "predictor.names")]),]

coef.plot <- plts_immEff_diet$coef.plot +
  ggrepel::geom_text_repel(
    data = df, size = 4, fontface = "bold",
    aes(x = leaf.position, y = value, label = predictor.names, color = Family)
  )
coef.plot
```

```{r diet-treeDA-immEff-tree-labs, fig.width=12, fig.height=8}
combine_plot_and_tree(coef.plot, plts_immEff_diet$tree.plot, tree.height = 1)
```



```{r}
df %>% select(value, Seq_ID, Family:OrgName)
```


```{r}
load( file = "output/fpca_clust_res_diet.rda")

diet2plot.fclust <- diet_fclust_subjFit %>%
  left_join(TAXTAB, by = c("Feature_ID" = "Seq_ID")) %>%
  group_by(Feature_ID) %>%
  mutate(
    n_cluster1 = sum(Cluster == 1),
    n_cluster2 = sum(Cluster == 2),
    majorityCluster = ifelse(n_cluster1 > n_cluster2, 1, 2)
  ) %>% 
  ungroup() %>%
  mutate(
    Subject_Cluster = ifelse(Cluster == majorityCluster, "Majority", "Minority")) 


diet2plot <- diet.rsv.subset %>% 
  left_join(
    diet2plot.fclust %>% 
      select(-value, -time) %>%
      distinct() %>%
      dplyr::rename(Seq_ID = Feature_ID,  Subject = Replicate_ID) 
  ) 

```

```{r immEff-diet, fig.width=12, fig.height=10}
seq_to_plot <- df$Seq_ID[1:20]
diet2plot.fclust %>%
    filter(Feature_ID %in% seq_to_plot) %>%
ggplot(aes(x = time, y = value, color = Subject_Cluster)) +
  geom_line(
    aes(group = Replicate_ID),
    alpha = 0.3, size = 0.5
  ) +
  geom_smooth(se = FALSE) +
  geom_point(
    data = diet2plot %>%   filter(Seq_ID %in% seq_to_plot),
    aes(x = Diet_RelDay, y = abundance),
    size = 0.3, alpha = 0.5
  ) +
  geom_vline(xintercept = 0, lwd = 1, color = "orange") +
  geom_vline(xintercept = 4, lwd = 1, color = "orange") +
  geom_line(
    data = diet_fclust_mu %>% 
      filter(Feature_ID %in% seq_to_plot) %>% 
      left_join(TAXTAB, by = c("Feature_ID" = "Seq_ID")),
    color = "red", size = 1
  ) +
  scale_color_manual(values = c( "grey17", "deepskyblue2")) +
  facet_wrap(~ OrgName, scales = "free", ncol = 4) +
  ylab("Variance stabilized counts, asinh(cnt)") +
  theme(strip.text = element_text(family="Helvetica-Narrow", size = 10)) +
  scale_x_continuous(name = "Days from initial antibiotic dose",
                     breaks = seq(-40, 120, 20), labels =  seq(-40, 120, 20),
                 limits = c(NA, NA)) 
```



### Long Term Effect



```{r}
diet_longEff <- subset_samples(diet, LongtermEff %in%  c("PrePert", "PostPert")) 
diet_longEff <- filter_taxa(diet_longEff, minTaxaSum=10, minTaxaPrev=3, minNoSubj=3)
diet_longEff
```

```{r}
table(sample_data(diet_longEff)$LongtermEff)
```



```{r, eval = FALSE}
dietlongEff.treeda100 = treeDA::treeda(
  response = sample_data(diet_longEff)$LongtermEff,
  predictors = asinh(t(otu_table(diet_longEff))),
  tree = phy_tree(diet_longEff), 
  p = 100, scale = FALSE)

save(list = c("abxImmEff.treeda", "abxlongEff.treeda", "dietImmEff.treeda", "dietlongEff.treeda", "dietlongEff.treeda100"),
     file = "output/treeDA_and_agpca.rda")
```

```{r}
dietlongEff.treeda100

# An object of class treeda
# -------------------------
# 50 predictors in the expanded space
# were selected, corresponding to 949 
# leaves on the tree
# -------------------------
# Confusion matrix:
#           predicted
# truth      PostPert PrePert
#   PostPert       71     100
#   PrePert        28     406
```




```{r}
ggplot(data.frame(sample_data(diet_longEff), 
                  projections = dietlongEff.treeda100$projections)) +
  geom_point(aes(x = Subject, y = projections, color = LongtermEff)) +
  theme(axis.text.x = element_text(angle = 90))
```


```{r}
nTaxa <- 10; thresh <- 1e-3
beta <- as.numeric(dietlongEff.treeda100$leafCoefficients$beta)
taxtab.dietlongEff <- data.frame(
  beta = beta,
  Seq_ID = rownames(as(tax_table(diet_longEff), "matrix")), 
  stringsAsFactors = FALSE) %>%
  left_join(TAXTAB)

freq_family <- taxtab.dietlongEff %>%
  group_by(Family) %>%
  summarise(Freq = n()) %>%
  filter(!is.na(Family)) %>%
  arrange(desc(Freq))

family_levels <- unique(c(
  as.character(freq_family$Family[1:nTaxa]),
  as.character(taxtab.dietlongEff$Family[abs(beta) > thresh])))[1:nTaxa]

taxtab.dietlongEff$family <- factor(taxtab.dietlongEff$Family, levels = family_levels)
```


```{r diet-treeDA-longEff-tree, fig.width=12, fig.height=7.5}
plts_longEff_diet <- plot_coefficients(dietlongEff.treeda100, color = taxtab.dietlongEff$family)
combine_plot_and_tree(plts_longEff_diet$coef.plot, plts_longEff_diet$tree.plot, tree.height = 1)
```



```{r diet-treeDA-longEff-labs, fig.width=12, fig.height=6}
df <- plts_longEff_diet$df %>% 
  left_join(TAXTAB, by =c("predictor.names" = "Seq_ID")) %>%
  mutate(
        Family = taxtab.dietlongEff$family,
        Species = ifelse(is.na(Species), "", as.character(Species)),
        Genus = ifelse(is.na(Genus), "", as.character(Genus)),
        org.name = paste(Genus, Species),
        Seq_ID = predictor.names,
        predictor.names = ifelse(org.name == " ", predictor.names, org.name)) %>%
  filter(abs(value) > 0.025) 

df <- df[!duplicated(df[, c("value", "predictor.names")]),]

coef.plot <- plts_longEff_diet$coef.plot +
  ggrepel::geom_text_repel(
    data = df, size = 4, fontface = "bold",
    aes(x = leaf.position, y = value, label = predictor.names, color = Family)
  )
coef.plot
```

```{r diet-treeDA-longEff-tree-labs, fig.width=12, fig.height=8}
combine_plot_and_tree(coef.plot, plts_longEff_diet$tree.plot, tree.height = 1)
```

```{r}
df %>% select(value, Seq_ID, Family:OrgName)
```

```{r longEff-diet, fig.width=12, fig.height=10}
seq_to_plot <- df$Seq_ID[1:20]
diet2plot.fclust %>%
    filter(Feature_ID %in% seq_to_plot) %>%
ggplot(aes(x = time, y = value, color = Subject_Cluster)) +
  geom_line(
    aes(group = Replicate_ID),
    alpha = 0.3, size = 0.5
  ) +
  geom_smooth(se = FALSE) +
  geom_point(
    data = diet2plot %>%   filter(Seq_ID %in% seq_to_plot),
    aes(x = Diet_RelDay, y = abundance),
    size = 0.3, alpha = 0.5
  ) +
  geom_vline(xintercept = 0, lwd = 1, color = "orange") +
  geom_vline(xintercept = 4, lwd = 1, color = "orange") +
  geom_line(
    data = diet_fclust_mu %>% 
      filter(Feature_ID %in% seq_to_plot) %>% 
      left_join(TAXTAB, by = c("Feature_ID" = "Seq_ID")),
    color = "red", size = 1
  ) +
  scale_color_manual(values = c( "grey17", "deepskyblue2")) +
  facet_wrap(~ OrgName, scales = "free", ncol = 4) +
  ylab("Variance stabilized counts, asinh(cnt)") +
  theme(strip.text = element_text(family="Helvetica-Narrow", size = 10)) +
  scale_x_continuous(name = "Days from diet initiation",
                     breaks = seq(-40, 120, 20), labels =  seq(-40, 120, 20),
                 limits = c(NA, NA)) 
```




```{r}
sessionInfo()
```



