---
title: "Trends in the perturbation/resilience study"
output: html_document
---

```{r knitr, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

```{r setup, message=FALSE}
library("phyloseq")
library("RColorBrewer")
library("tidyverse")
library("readxl")
library("data.table")
library("PMA")
datadir <- "../../data/"
curdir <- getwd()
```


## Load data

```{r}
# Sample Information
meas_info <- read_xlsx(
  file.path(datadir, "sample_info/Mapping_File_19Oct2018.xlsx"),
  "Meas", range = cell_cols(1:7))
names(meas_info) <- meas_info[1, ]
meas_info <- meas_info[-1, ] %>%
  rename(Samp_ID = SampID)

interv_levs <- c("NoInterv", "PreDiet", "MidDiet", "PostDiet", 
                 "PreCC", "MidCC","PostCC", "PreAbx", "MidAbx", "PostAbx")
samp <- read_xlsx(
  file.path(datadir, "sample_info/Mapping_File_19Oct2018.xlsx"),
  "Samp", skip = 1) %>%
  mutate(
    Diet_Interval = ifelse(Diet_Interval == "NA", "NoInterv", Diet_Interval),
    CC_Interval = ifelse(CC_Interval == "NA", "NoInterv", CC_Interval),
    Abx_Interval = ifelse(Abx_Interval == "NA", "NoInterv", Abx_Interval),
    Diet_Interval = factor(Diet_Interval, interv_levs),
    CC_Interval = factor(CC_Interval, interv_levs),
    Abx_Interval = factor(Abx_Interval, interv_levs)
  ) %>%
  filter(Samp_Type != "ExtrCont")

meas_info <- meas_info %>% select(Meas_ID, Samp_ID) %>%
  left_join(samp)
dim(meas_info)
rm(samp)
```


```{r}
head(meas_info)
```










```{r}
sessionInfo()
```

